### ISSUE TITLE
Resolving path to editor / preview.sh not working

### ISSUE THREAD

**Issue by appelgriebsch** [roosta/fif#1]
Thanks for this nice shell extension. Did sync it to my local machine and added the required sourcing in my .bashrc. I can trigger the fif command successfully, but it complains about not finding the preview.sh (and when selecting a file also for editor.sh). I noticed it is looking in /usr/bin/ for those files... shouldn't it be resolved based on the path the script is located in?

**Comment by roosta** [comment]
Hi, thanks for checking out fif and for the issue. This plugin isn't truly ready for consumption yet, as there are multiple issues that I haven't fixed yet. Hopefully 0578f57 resolves this particular issue.

**Comment by roosta** [comment]
Turns out `$0` is a bit inconsistent, so I used `$BASH_SOURCE` to resolve path correctly (hopefully)

**Comment by appelgriebsch** [comment]
works well, thanks!

**Comment by roosta** [comment]
Let me know if you find any other issues, I'll see about fixing them as soon as possible. Great to have a couple of new eyes on this.
